#!/usr/bin/env node

const program = require('commander')

program
  .command('legit [host]', 'is [host] a legit target for assessment?')
  .command('ssllabs [host]', 'request SSL Labs analysis')
  .parse(process.argv)
