#!/usr/bin/env node

const program = require('commander')
const check = require('./SSLLabsCheck')

program
  .option('-v, --verbose', 'report progress')
  .parse(process.argv)

const host = program.args[0]

check(host, program.verbose).then(function(result) {
  let grades = result.data.endpoints.map((ep) => {
    return ep.grade
  })
  console.log(grades)
}).catch(function(err){
  console.log(err)
})
