#!/usr/bin/env node

const program = require('commander')
const legit = require('./LegitimacyCheck')
const httpsOnly = require('./HTTPSOnlyCheck')

program
  .parse(process.argv)

const host = program.args[0]

const flatten = (arr, result = []) => {
  for (let i = 0, length = arr.length; i < length; i++) {
    const value = arr[i]
    if (Array.isArray(value)) {
      flatten(value, result)
    } else {
      result.push(value)
    }
  }
  return result
}

const check = (host) => {
  return Promise.all(flatten([legit(host), httpsOnly(host)]))
}

check(host).then((results) => {
  results.forEach((result) => {
    console.log(`\t${result.msg}`)
  })
}).catch((err) => {
  console.log(err)
})
