#!/usr/bin/env node

const program = require('commander')
const check = require('./HTTPSOnlyCheck')

program
  .parse(process.argv)

const host = program.args[0]

check(host).then((result) => {
  console.log(`\t${result}`)
}).catch((err) => {
  console.log(`\t${err}`)
})
