#!/usr/bin/env node

const program = require('commander')
const check = require('./SSLLabsCheck')

program
  .option('-v, --verbose', 'report progress')
  .parse(process.argv)

const host = program.args[0]

check(host, program.verbose).then(function(result) {
  console.log(`\t${result.msg}`)
}).catch(function(err){
  console.log(`\tfail: ${err}`)
})
