#!/usr/bin/env node

const program = require('commander')

program
  .command('legit [host]', 'is [host] a legit target for assessment?')
  .command('https-only [host]', 'is [host] only available over HTTPS?')
  .command('ssllabs [host]', 'request SSL Labs analysis')
  .command('all-checks [host]', 'does [host] pass all checks?')
  .parse(process.argv)
