#!/usr/bin/env node

const program = require('commander')
const check = require('./LegitimacyCheck')

program
  .parse(process.argv)

const host = program.args[0]

check(host).then((results) => {
  results.forEach((result) => {
    console.log(`\t${result}`)
  })
}).catch((err) => {
  console.log(err)
})
